name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1.11.2
        id: release
        with:
          changelog-file: true
          github-token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - run: GOPROXY=proxy.golang.org go list -m github.com/adaptavist/bitbucket_pipelines_client@v${{ steps.release.outputs.version }}
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: latest
      - run: GOPROXY=proxy.golang.org go list -m github.com/adaptavist/bitbucket_pipelines_client@latest
